stages:
  - build
  - quality
  - notify

image: "gradle:8.11.0-jdk21-alpine"

build:
  stage: build
  script: ./gradlew build

test:
  stage: quality
  script: ./gradlew test

scan:
  stage: quality
  script:
    - > 
      ./gradlew sonar 
      -D"sonar.host.url=$SONAR_HOST_URL" 
      -D"sonar.token=$SONAR_TOKEN" 
      -D"sonar.projectKey=$SONAR_PROJECT_KEY" 
      -D"sonar.organization=$SONAR_ORG"

notify:
  stage: notify
  script:
    - echo "Sending notification to Telegram"
    - >
      curl -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" 
      -d "chat_id=${TELEGRAM_TO}" 
      -d "text=${GITLAB_USER_NAME} -> ${CI_PROJECT_PATH}\n\n${CI_COMMIT_MESSAGE}\n\n*${CI_JOB_STATUS}*\n\nSee changes: ${CI_REPOSITORY_URL}/commit/${CI_COMMIT_SHA}" 
      -d "parse_mode=Markdown"