services:
  service:
    build:
     context: .
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider localhost:8080/health || exit 1"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 20s
    depends_on:
      - db
      - keydb
      - kafka
    environment:
      APP_NAME: "auth-service"
      KAFKA_BROKERS: "kafka:9092"
      KEYDB_HOST: "redis://keydb:6379"
      DB_HOST: "db"
    ports:
      - "8080:8080"

  db:
    image: postgres:16.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: auth_service
      POSTGRES_USER: auth_service
      POSTGRES_DB: auth_service

  keydb:
    image: eqalpha/keydb
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: 0.0.0.0
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
    volumes:
      - zk-data:/var/lib/zookeeper/data
      - zk-txn-logs:/var/lib/zookeeper/log
      - zk-secrets:/etc/zookeeper/secrets

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LOCAL://kafka:29092,DOCKER://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LOCAL://localhost:29092, DOCKER://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0


volumes:
  pg_data: { }
  zk-data: { }
  zk-txn-logs: { }
  zk-secrets: { }
  kafka-data: { }
  kafka-secrets: { }
