services:
  service:
    build:
     context: .
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider localhost:8080/health || exit 1"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 20s
    depends_on:
      - db
      - kafka
    environment:
      APP_NAME: "auth-service"
      KAFKA_BROKERS: "kafka:9092"
      DB_HOST: "db"
      OTEL_HOST: "collector"
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://collector:4318/v1/metrics"
    ports:
      - "8080:8080"

  db:
    image: postgres:16.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: auth_service
      POSTGRES_USER: auth_service
      POSTGRES_DB: auth_service

  kafka:
    image: confluentinc/cp-enterprise-kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_LISTENERS: LOCAL://kafka:29092,DOCKER://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LOCAL://localhost:29092, DOCKER://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  collector:
    image: otel/opentelemetry-collector-contrib:0.102.1
    volumes:
      - ./config/config.yaml:/etc/config.yaml
    command: [ "--config=/etc/config.yaml" ]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "4319:4319"


volumes:
  pg_data: { }
  zk-data: { }
  zk-txn-logs: { }
  zk-secrets: { }
  kafka-data: { }
  kafka-secrets: { }
