ktor:
  deployment:
    port: 8080
  application:
    modules:
      - ru.somarov.auth.infrastructure.AppConfigKt.config
  environment:
    timezone: "UTC"
  monitoring:
    name: "$APP_NAME:auth-service"
    instance: "$HOSTNAME:undefined"
    build-props-path: "/META-INF/build-info.properties"
    protocol: "http"
    host: "$OTEL_HOST:localhost"
    logs:
      port: "4317"
    metrics:
      port: "4318"
    tracing:
      port: "4319"
      probability: "1.0"
  db:
    host: "$DB_HOST:localhost"
    port: "$DB_PORT:5432"
    name: "$DB_NAME:auth_service"
    schema: "$DB_SCHEMA:auth_service"
    user: "$DB_USER:auth_service"
    password: "$DB_PASSWORD:auth_service"
    connection-timeout: "$DB_CONNECTION_TIMEOUT:PT5S"
    statement-timeout: "$DB_STATEMENT_TIMEOUT:PT5S"
    pool:
      max-size: "$DB_POOL_MAX_SIZE:8"
      min-idle: "$DB_POOL_MIN_IDLE:2"
      max-idle-time: "$DB_POOL_MAX_IDLE_TIME:PT1M"
      max-life-time: "$DB_POOL_MAX_LIFE_TIME:PT1M"
      validation-query: "$DB_POOL_VALIDATION_QUERY:SELECT 1"
  cache:
    url: "$KEYDB_HOST:redis://localhost:6379"
  kafka:
    brokers: "$KAFKA_BROKERS:localhost:9092"
    producers:
      retry:
        enabled: "$KAFKA_RETRY_PRODUCING_ENABLED:false"
        topic: "auth_service_retry"
        max-in-flight: "1"
      dlq:
        enabled: "$KAFKA_RETRY_DLQ_ENABLED:false"
        topic: "auth_service_dlq"
        max-in-flight: "1"
      registration:
        enabled: "$KAFKA_REGISTRATION_ENABLED:false"
        topic: "auth_service_registration_broadcast"
        max-in-flight: "1"
      auth:
        enabled: "$KAFKA_AU_ENABLED:false"
        topic: "auth_service_auth_broadcast"
        max-in-flight: "1"
  auth:
    access:
      duration-millis: 50000
      key-path: key8.pem
      issuer: auth
      audience: auth
    refresh:
      duration-millis: 50000
      key-path: key8.pem
      issuer: auth
      audience: auth
    userid:
      duration-millis: 50000
      key-path: key8.pem
      issuer: auth
      audience: auth