ktor:
  development: true
  deployment:
    watch:
      - classes
    port: 8080
  application:
    modules:
      - ru.somarov.auth.infrastructure.ApplicationConfigKt.config

application:
  name: "$APP_NAME:undefined"
  instance: "$APP_INSTANCE:undefined" # TODO: add kuber var
  otlp:
    url: "$OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317"
