ktor:
  development: true
  deployment:
    watch:
      - classes
    port: 8080
  application:
    modules:
      - ru.somarov.auth.infrastructure.config.ApplicationConfigKt.config

application:
  name: "$APP_NAME:undefined"
  instance: "HOSTNAME:undefined"
  otel:
    protocol: "http"
    host: "localhost"
    logsPort: "4317"
    metricsPort: "4317"
    tracingPort: "4317"
    tracingProbability: "0.1"
